In [1]:
import pandas as pd
import datetime as dt
import numpy as np
#from libs.logger import Logger
import logging
from libs.s3 import S3
import pyodbc
from client_based_code.kickz_code import CONNECTION_STRING

logger = logging.getLogger(__name__)

from libs.logger import Logger
logger = Logger().get_print_logger()

In [ ]:
gs_path_token = './auth_files/token.pickle'
gs_path_client_secret = './auth_files/client_secret_708086849726-edgo6g4pigkf5rj0qc52rir18oso0kto.apps.googleusercontent.com.json'
gs_spreadsheet_id = '1PHzUwQEZ5gLmf32D3Akx_qL5iFta8HuCnZWtWVb3bTk'

from libs.google_sheets import GoogleSheetsApi

gapi = GoogleSheetsApi(
    path_token = gs_path_token,
    path_client_secret = gs_path_client_secret
)

In [ ]:
df_pts = gapi.google_sheet2df(gs_spreadsheet_id, 'products_to_score')

In [ ]:
SQL = 'SELECT TOP 10 *  FROM [rawone11].[v_pim_articles_data]'

In [134]:
SQL = """
SELECT 
            LOWER(TRIM(style)) AS style,
            country AS country_code,
            UPPER(currency) AS currency,
            sale_price AS price_local,
            rrp AS base_price_local
        FROM [rawKickz].[product_sales_price]
        WHERE rrp IS NOT NULL
            AND rrp != 0
            AND sale_price IS NOT NULL
            AND sale_price != 0
"""

with pyodbc.connect(CONNECTION_STRING) as con:
    df = pd.read_sql(SQL, con)
    
df[df['style'] == 'ah8050-002']
# df[df['style'] == '1110-007-120']

/tmp/ipykernel_4123429/2293156146.py:16: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(SQL, con)

            style country_code currency  price_local  base_price_local
3903   ah8050-002           BE      EUR        97.95            159.95
4358   ah8050-002           AT      EUR        97.95            159.95
6831   ah8050-002           CH      CHF       113.95            184.95
13364  ah8050-002           ES      EUR        97.95            159.95
38482  ah8050-002           GB      GBP       110.95            136.95
44755  ah8050-002           FR      EUR       129.90            159.95
47831  ah8050-002           IT      EUR        97.95            159.95
52917  ah8050-002           FI      EUR        97.95            159.95
70294  ah8050-002           DE      EUR        97.95            159.95
70848  ah8050-002           DK      EUR        97.95            159.95

In [135]:
styles

['dy6595',
 'dq7332-091',
 'hz6758dbbkayil',
 'jz0523',
 'da5718-010',
 'kc9633',
 'dy6620',
 'hm9965-100',
 'gy8787',
 'i035614-1yl4o',
 'b-brans17ctp-b',
 'sx7666-100',
 '560845c-001',
 'do9563-504',
 'hm0285-100',
 'hq6638',
 'if4726',
 'h04984',
 'jm2663',
 'gz5920',
 '1109-010-160',
 'kv6810',
 'hz6758dbbobst',
 'b7g3850',
 'ah8050-002',
 'hd2773',
 'dy6621',
 'ar0456',
 'xp7ljepopm3x',
 '1110-007-120',
 'ml373-kn2',
 '6566-weiss',
 'fn3861-063']

In [140]:
df[(df['style'].isin(styles)) & (df['country_code'] == 'DE')]

               style country_code currency  price_local  base_price_local
5021     560845c-001           DE      EUR        79.95             84.95
20695         kc9633           DE      EUR        11.95             11.95
28489         jm2663           DE      EUR        33.95             29.95
41484         gz5920           DE      EUR        26.95             27.95
44013        b7g3850           DE      EUR        38.95             49.95
44584     da5718-010           DE      EUR        12.95             19.95
45700  i035614-1yl4o           DE      EUR       128.95            248.95
47253         hq6638           DE      EUR        82.95             89.95
56603         jz0523           DE      EUR        11.95             11.95
57086     hm9965-100           DE      EUR        79.95             79.95
60655         kv6810           DE      EUR        17.95             17.95
70294     ah8050-002           DE      EUR        97.95            159.95

In [138]:
df

                style country_code currency  price_local  base_price_local
0           a60424783           DE      EUR        17.95             29.95
1        60759093-301           BE      EUR        15.95             27.95
2        dk0a4xk6khk1           FI      EUR        48.95             66.95
3              jq0314           GB      GBP        76.95             76.95
4         3027603-100           NL      EUR        83.95            139.95
...               ...          ...      ...          ...               ...
75218     ptf7707-rey           DK      EUR        24.95             24.95
75219  smjygs18192-om           IT      EUR        73.95            121.95
75220   i033156-0f44j           DE      EUR        35.95             58.95
75221       635023-13           ES      EUR       107.95            119.95
75222  kxm252-010-1-k           NL      EUR        28.95             29.95

[75223 rows x 5 columns]

In [129]:
import pandas as pd

df = pd.read_parquet('backup/df_recommendations_20260512.parquet')
df[df['style'] == 'ah8050-002']

,brand,product_name,style,price,price_from,base_price,price_original_currency,category,country_code,product_demand,...,item_category,item_group0,item_group1,item_group2,demand_key,demand_key_original,group_logic,recom_change,recom_price,date
1170,nike,nike air max 270 black c002,ah8050-002,NaN,NaN,NaN,NaN,CARRYOVERS,AT,1.307692,...,Lifestyle,Footwear,Sneaker,Running,ah8050-002,ah8050-002,OFF,NOT ENOUGH DATA,NaN,2026-05-12 23:59:03
1171,nike,nike air max 270 black c002,ah8050-002,NaN,NaN,NaN,NaN,CARRYOVERS,FR,1.307692,...,Lifestyle,Footwear,Sneaker,Running,ah8050-002,ah8050-002,OFF,NOT ENOUGH DATA,NaN,2026-05-12 23:59:03
1172,nike,nike air max 270 black c002,ah8050-002,NaN,NaN,NaN,NaN,CARRYOVERS,DE,1.307692,...,Lifestyle,Footwear,Sneaker,Running,ah8050-002,ah8050-002,OFF,NOT ENOUGH DATA,NaN,2026-05-12 23:59:03
1173,nike,nike air max 270 black c002,ah8050-002,NaN,NaN,NaN,NaN,CARRYOVERS,CH,1.307692,...,Lifestyle,Footwear,Sneaker,Running,ah8050-002,ah8050-002,OFF,NOT ENOUGH DATA,NaN,2026-05-12 23:59:03
1174,nike,nike air max 270 black c002,ah8050-002,NaN,NaN,NaN,NaN,CARRYOVERS,GB,1.307692,...,Lifestyle,Footwear,Sneaker,Running,ah8050-002,ah8050-002,OFF,NOT ENOUGH DATA,NaN,2026-05-12 23:59:03

In [130]:
styles = list(set(df[(df['category'] == 'CARRYOVERS')
  & (df['recom_change'] == 'NOT ENOUGH DATA')
  ]["style"].to_list()))

['dy6595',
 'dq7332-091',
 'hz6758dbbkayil',
 'jz0523',
 'da5718-010',
 'kc9633',
 'dy6620',
 'hm9965-100',
 'gy8787',
 'i035614-1yl4o',
 'b-brans17ctp-b',
 'sx7666-100',
 '560845c-001',
 'do9563-504',
 'hm0285-100',
 'hq6638',
 'if4726',
 'h04984',
 'jm2663',
 'gz5920',
 '1109-010-160',
 'kv6810',
 'hz6758dbbobst',
 'b7g3850',
 'ah8050-002',
 'hd2773',
 'dy6621',
 'ar0456',
 'xp7ljepopm3x',
 '1110-007-120',
 'ml373-kn2',
 '6566-weiss',
 'fn3861-063']

In [ ]:
from client_based_code.kickz_code import S3ProductsToScore, get_orders
from libs.help_functions import stylesAutoPricing2dict

In [ ]:
#S3ProductsToScore.store(df_products_to_score)

In [ ]:
df_products_to_score = S3ProductsToScore.load_latest()

In [ ]:
df = df_products_to_score

In [ ]:
autopricing_cols = [col for col in  df.columns if 'auto_pricing' in col]
df.drop_duplicates('style', keep='last', inplace=True)

In [ ]:
for col in autopricing_cols:
    try:
        df[col].astype(int).astype(bool)
    except:
        print(col)

In [ ]:
import datetime as dt

In [ ]:
df_products_to_score['date_added'] = df_products_to_score['date_added'] - dt.timedelta(days=30)

In [ ]:
to_date = dt.date.today()
from_date = to_date - dt.timedelta(days=30)

In [ ]:
df_orders = get_orders(from_date, to_date)

In [ ]:
df_orders_grouped = df_orders.groupby(['brand','style'], as_index=False)['quantity'].sum()

In [ ]:
df_final = (
    df_products_to_score[['brand','style','product_name']]
    .merge(df_orders_grouped, on=['brand','style'], how='inner')
    .fillna(0)
    .sort_values('quantity',ascending=False)\
    .reset_index(drop=True)
)

In [ ]:
df_final

In [1]:
from client_based_code.kickz_code import get_all_products, get_orders,get_google_ads_data,get_style_items_categories,get_quantities_from_inventory

In [ ]:
df = get_google_ads_data(dt.date(2025,9,1), dt.date.today())

In [ ]:
df

In [ ]:
df= get_quantities_from_inventory()

In [ ]:
df

,brand,product_name,style,price,price_from,base_price,price_original_currency,category,country_code,product_demand,...,item_category,item_group0,item_group1,item_group2,demand_key,demand_key_original,group_logic,recom_change,recom_price,date
1170,nike,nike air max 270 black c002,ah8050-002,NaN,NaN,NaN,NaN,CARRYOVERS,AT,1.307692,...,Lifestyle,Footwear,Sneaker,Running,ah8050-002,ah8050-002,OFF,NOT ENOUGH DATA,NaN,2026-05-12 23:59:03
1171,nike,nike air max 270 black c002,ah8050-002,NaN,NaN,NaN,NaN,CARRYOVERS,FR,1.307692,...,Lifestyle,Footwear,Sneaker,Running,ah8050-002,ah8050-002,OFF,NOT ENOUGH DATA,NaN,2026-05-12 23:59:03
1172,nike,nike air max 270 black c002,ah8050-002,NaN,NaN,NaN,NaN,CARRYOVERS,DE,1.307692,...,Lifestyle,Footwear,Sneaker,Running,ah8050-002,ah8050-002,OFF,NOT ENOUGH DATA,NaN,2026-05-12 23:59:03
1173,nike,nike air max 270 black c002,ah8050-002,NaN,NaN,NaN,NaN,CARRYOVERS,CH,1.307692,...,Lifestyle,Footwear,Sneaker,Running,ah8050-002,ah8050-002,OFF,NOT ENOUGH DATA,NaN,2026-05-12 23:59:03
1174,nike,nike air max 270 black c002,ah8050-002,NaN,NaN,NaN,NaN,CARRYOVERS,GB,1.307692,...,Lifestyle,Footwear,Sneaker,Running,ah8050-002,ah8050-002,OFF,NOT ENOUGH DATA,NaN,2026-05-12 23:59:03

,brand,product_name,style,price,price_from,base_price,price_original_currency,category,country_code,product_demand,...,item_category,item_group0,item_group1,item_group2,demand_key,demand_key_original,group_logic,recom_change,recom_price,date
1170,nike,nike air max 270 black c002,ah8050-002,NaN,NaN,NaN,NaN,CARRYOVERS,AT,1.307692,...,Lifestyle,Footwear,Sneaker,Running,ah8050-002,ah8050-002,OFF,NOT ENOUGH DATA,NaN,2026-05-12 23:59:03
1171,nike,nike air max 270 black c002,ah8050-002,NaN,NaN,NaN,NaN,CARRYOVERS,FR,1.307692,...,Lifestyle,Footwear,Sneaker,Running,ah8050-002,ah8050-002,OFF,NOT ENOUGH DATA,NaN,2026-05-12 23:59:03
1172,nike,nike air max 270 black c002,ah8050-002,NaN,NaN,NaN,NaN,CARRYOVERS,DE,1.307692,...,Lifestyle,Footwear,Sneaker,Running,ah8050-002,ah8050-002,OFF,NOT ENOUGH DATA,NaN,2026-05-12 23:59:03
1173,nike,nike air max 270 black c002,ah8050-002,NaN,NaN,NaN,NaN,CARRYOVERS,CH,1.307692,...,Lifestyle,Footwear,Sneaker,Running,ah8050-002,ah8050-002,OFF,NOT ENOUGH DATA,NaN,2026-05-12 23:59:03
1174,nike,nike air max 270 black c002,ah8050-002,NaN,NaN,NaN,NaN,CARRYOVERS,GB,1.307692,...,Lifestyle,Footwear,Sneaker,Running,ah8050-002,ah8050-002,OFF,NOT ENOUGH DATA,NaN,2026-05-12 23:59:03

In [ ]:
df.groupby(['category','recom_change']).size()

In [ ]:
df[['style', 'country_code','impressions_demand','ctr_demand']]

In [ ]:
import datetime as dt 
from client_based_code.kickz_code import get_google_ads_data

def adjust_gads_data(df_gads):
    df_gads.loc[df_gads['clicks'] > df_gads['impressions'],'impressions'] = df_gads.loc[df_gads['clicks']> df_gads['impressions'],'clicks']
    df_gads['ctr'] = df_gads['clicks'].divide(df_gads['impressions']).fillna(0)

    return df_gads

today = dt.date.today()

last_week_start = today - dt.timedelta(7)
week_before_start = today - dt.timedelta(14)

df_gads_last_week = adjust_gads_data(get_google_ads_data(last_week_start))
df_gads_week_before = adjust_gads_data(get_google_ads_data(week_before_start, last_week_start))

df_gads_ratio = df_gads_last_week.merge(
    df_gads_week_before,
    left_on = ['country_code','style','brand'],
    right_on = ['country_code','style', 'brand'],
    suffixes = ('_last_week','_week_before')
    )\
     .assign(
        clicks_ratio = lambda x: x['clicks_last_week'] / x['clicks_week_before'],
        impresions_ratio = lambda x: x['impressions_last_week'] / x['impressions_week_before'],
        ctr_ratio =lambda x: x['ctr_last_week'] / x['ctr_week_before']
    )\
    .fillna(0)

df_gads_ratio = df_gads_ratio[['country_code','style','clicks_ratio', 'impresions_ratio', 'ctr_ratio']]

In [ ]:
df_gads_ratio[df_gads_ratio['style'].str.contains('5620')]

In [ ]:
df[['style', 'country_code']]

In [ ]:
df_gads_ratio.merge(df[['style', 'country_code']], on=['style', 'country_code'])

In [ ]:
df[df['style'] == 'fn2651-100'][['country_code', 'impressions_demand','ctr_demand']]

In [ ]:
import pandas as pd
import logging
import sentry_sdk
from sentry_sdk.integrations.logging import LoggingIntegration
from libs.logger import Logger
from update_prices import PricingLogic
from settings import kickz

In [ ]:
# logging
logger = Logger().get_full_logger(
    filename='./logs/update_prices.log',
    log_level=logging.INFO,
    print_level=logging.INFO
)

In [ ]:
updater = PricingLogic(settings=kickz)
#updater.run(insert_into_production=False, insert_into_s3=False)

In [ ]:
updater._load_conversion_rates()

In [ ]:
df_recommendations = pd.read_parquet('backup/df_recommendations_20250929.parquet')

In [ ]:
df_recommendations

In [ ]:
df_recommendations = df_recommendations[
    (~df_recommendations['recom_price'].isnull())
  & (~df_recommendations['base_price'].isnull())
  & (df_recommendations['recom_change'] != 'NOT ENOUGH DATA')
  & (df_recommendations['master_switch'] == 1)
]

# CHECK NA CHYBNE CENY 
MAX_DISCOUNT = 0.1 # 1 - maximalna mozna zlava ktoru je mozne dat na produkt 
df_recommendations = df_recommendations[
    (df_recommendations['recom_price'].between(df_recommendations['base_price']*MAX_DISCOUNT, df_recommendations['base_price']))
  & (df_recommendations['base_price'] > 0)
]

# currency mapper
df_recommendations['currency'] = df_recommendations['country_code'].apply(lambda country_code: COUNTRY_CODE_CURRENCY_MAPPER[country_code])

In [ ]:
df_recommendations

In [ ]:
df_recommendations.apply(lambda row: row['recom_price'] * self.conversion_rates[row['currency']], axis=1)

In [ ]:
df_recommendations['recom_price_local_currency'] = df_recommendations.apply(lambda row: row['recom_price'] * self.conversion_rates[row['currency']], axis=1)

In [ ]:
df_recommendations = updater.df_recommendations

In [ ]:
df_recommendations['our_min_possible_price'] = df_recommendations['base_price'] * (1 - df_recommendations['max_discount'])
df_recommendations['our_max_possible_price'] = df_recommendations['base_price'] * (1 - df_recommendations['min_discount'])

In [ ]:
df_imp = df_recommendations[df_recommendations['category'] != 'ST']
df_st = df_recommendations[df_recommendations['category'] == 'ST'].query('country_code == "DE"')

In [ ]:
df_imp[['date','brand','style', 'country_code','base_price','price','recom_price','recom_change',
        'min_discount', 'max_discount','impressions_demand', 'ctr_demand','total_demand',
        'sold_items_7_days','our_min_possible_price','our_max_possible_price']]

In [ ]:
from client_based_code.kickz_code import get_google_ads_data,get_quantities_from_inventory
import datetime as dt

In [ ]:
df_gads = get_google_ads_data(from_date=dt.date(2025,9,16))

In [ ]:
df_gapi_714_ratios = updater.df_gapi_714_ratios

In [ ]:
df_gapi_714_ratios[df_gapi_714_ratios['style'] == 'ij5620']

In [ ]:
df_gads[df_gads['style'].str.contains('ij5620')]

In [ ]:
df_st[['date','brand','style', 'country_code','base_price','price','recom_price','recom_change',
        'min_discount', 'max_discount','sell_power_day','sell_power_week','is_new_product','last_day_sell_power_week','ST_setting','item_category',
       'season_length','days_from_season_start',
      'sold_items_day','sold_items_season','quantity_in_inventory']].dropna(subset=['base_price'])

In [ ]:
updater.discount_levels['ST'][('adidas originals','DE')]

In [ ]:
updater.st_settings

In [ ]:
df_quantity_in_inventory = get_quantities_from_inventory()

In [ ]:
df_quantity_in_inventory[df_quantity_in_inventory['style'] == 'ig6213']

In [ ]:
updater.quantities_in_inventory

In [ ]:
import pandas as pd

In [ ]:
df_recommendations = pd.read_parquet('backup/df_recommendations_20250924.parquet')

In [ ]:
df_recommendations[['brand','style','style_count_all_competitors', 'style_count_important_competitors',
       'style_all_competitors_list', 'style_all_competitors_links',
       'style_all_competitors_prices', 'style_all_competitors_in_stock',
       'style_all_competitors_price_change_day',
       'style_important_competitors_list', 'style_important_competitors_links',
       'style_important_competitors_prices',
       'style_important_competitors_in_stock',
       'style_important_competitors_price_change_day']].sort_values('style_count_all_competitors')

In [ ]:
df_recommendations.sort_values('style_count_all_competitors')

In [ ]:
df_top_100  = df_recommendations.groupby(['brand','style'], as_index=False)[['sold_items_14_days']].sum().sort_values('sold_items_14_days', ascending=False).head(100)

In [ ]:
df_recommendations['our_min_possible_price'] = df_recommendations['base_price'] * (1 - df_recommendations['max_discount'])
df_recommendations['our_max_possible_price'] = df_recommendations['base_price'] * (1 - df_recommendations['min_discount'])

In [ ]:
df_imp = df_recommendations[df_recommendations['category'] != 'ST']
df_st = df_recommendations[df_recommendations['category'] == 'ST'].query('country_code == "DE"')

In [ ]:
df_imp[['date','brand','style', 'country_code',
        'base_price','price','recom_price','recom_change',
        'min_discount', 'max_discount','impressions_demand', 'ctr_demand','total_demand',
        'sold_items_7_days','our_min_possible_price','our_max_possible_price']]

In [ ]:
df_st[['date','brand','style', 'country_code','base_price','price','recom_price','recom_change',
        'min_discount', 'max_discount','sell_power_day','sell_power_week','is_new_product','last_day_sell_power_week','ST_setting','item_category',
       'season_length','days_from_season_start',
      'sold_items_day','sold_items_season','quantity_in_inventory']].dropna(subset=['base_price'])['recom_change'].value_counts()

In [ ]:
df_sample = df_recommendations.merge(df_top_100[['brand','style']], on=['brand','style'])

In [ ]:
df_sample = df_sample[
    (~df_sample['recom_price'].isnull())
  & (~df_sample['base_price'].isnull())
  & (df_sample['recom_change'] != 'NOT ENOUGH DATA')
  & (df_sample['master_switch'] == 1)
]

In [ ]:
export_cols = [
    'date',
    'brand',
    'product_name', 
    'style',
    'country_code',
    'category' ,
    'price',
    'base_price',
    'recom_price',
    'our_min_possible_price',
    'our_max_possible_price',
]
df_sample['date'] = pd.to_datetime(df_sample['date']).dt.date
df_sample[export_cols].round(2).to_csv('kickz_results.csv', index=False)

In [ ]:
df_sample['date']

In [ ]:
from client_based_code.kickz_code import load_prices

In [ ]:
df_prices = load_prices()

In [ ]:
df_prices[df_prices['style'] == 'hq8707']

In [ ]:
df_prices['price_local'].round()

In [ ]:
round(5.10)

In [ ]:
from client_based_code.kickz_code import load_competitors_data
import datetime as dt

In [ ]:
from libs.help_functions import (
    COUNTRY_CODE_CURRENCY_MAPPER,
    is_our_shop,
    countryCompetitors2dict,
    clean_country_competitors,
    is_important_competitor
)

In [ ]:
from_date = dt.date.today() - dt.timedelta(days=3)
to_date = dt.date.today()

In [ ]:
import json

with open("auth_files/eas-core-34afc8b13f75.json", "r") as f:
    credentials = json.load(f)

In [ ]:
df = load_competitors_data(credentials, from_date, to_date, 90)

In [ ]:
df

In [ ]:
df['currency'] = df.apply(
    lambda row: COUNTRY_CODE_CURRENCY_MAPPER[row['country_code']] 
    if row['currency'] == '' 
    else row['currency'],
    axis=1
)

In [ ]:
df['is_our_shop'] = df.apply(
    lambda row: is_our_shop(row['url'], row['competitor_shop_name'],['kickz']), 
    axis=1
)

In [ ]:
df['is_important_competitor'] = df.apply(
    lambda row: is_important_competitor(row, country_competitors, 90),
    axis=1
)

In [ ]:
df[df['is_important_competitor']]

In [ ]:
df_competitors = gapi.google_sheet2df(gs_spreadsheet_id, 'relevant_competitors')
        
# dictionary
country_competitors = countryCompetitors2dict(df_competitors)

# Ocisti konkurenciu
# 'store.nike.com' => 'nike'
# 'https://www.runningpro.sk/' => 'runningpro'
# ...
country_competitors = clean_country_competitors(country_competitors)

In [ ]:
country_competitors

In [ ]:
import pandas as pd
import datetime as dt

In [ ]:
df = pd.read_parquet('s3://autopricing/kickz/products_to_score/20250925210451.parquet')

In [ ]:
pd.to_datetime(df['date_added'], dayfirst=False)

In [ ]:
df = pd.read_parquet('ap_export.parquet')

In [ ]:
SQL = """
SELECT      
        LOWER(TRIM(brand)) AS brand,
        LOWER(TRIM(style_id)) AS style,
        TRIM(material_number) AS material_number
FROM [rawone11].[v_pim_articles_data]
WHERE item_shop_active_kickz = 1
    AND name IS NOT NULL
    AND style_id IS NOT NULL
    AND brand IS NOT NULL;
"""

In [ ]:
with pyodbc.connect(CONNECTION_STRING) as con:
    df_mapper = pd.read_sql(SQL, con)

In [ ]:
x = df.merge(df_mapper, on=['brand','style'])

In [ ]:
x['export_country_code'] = 'kickz-' + x['country_code']
x['export_status'] = 'DISCOUNT'
x['export_from_date'] = x['date'].dt.strftime("%Y-%m-%dT%H:00:00")
x['export_to_date'] = pd.to_datetime(dt.datetime(2100,1,1)).strftime("%Y-%m-%dT%H:00:00")

In [ ]:
df_export = x[['material_number', 'recom_price_local_currency','export_status','export_from_date','export_to_date','export_country_code','currency']]

In [ ]:
df_export

In [ ]:
csv_data = df_export.head(10).to_csv(index=False, header=False, sep=';')

In [ ]:
csv_data

In [ ]:
def generate_filename(prefix="master/hotfolder/kickz/prices"):
    # current UTC time
    now = dt.datetime.now(dt.timezone.utc)
    
    # Unix timestamp in milliseconds
    ts_millis = int(now.timestamp() * 1000)
    
    # Human-readable timestamp (ISO-like) with milliseconds and Z
    dt_str = now.strftime("%Y-%m-%dT%H-%M-%S.%f")[:-3] + "Z"
    
    # Build filename
    filename = f"{prefix}-{ts_millis}.csv.{dt_str}"
    
    return filename

# Example usage
blob_name = generate_filename()

In [ ]:
blob_name

In [ ]:
connection_string = (
    "DefaultEndpointsProtocol=https;"
    "AccountName=o3w4n3fotw789gttys79amu;"
    "AccountKey=ltkXAjB76EPhkIfKM9Drmnn9k8XP8Zvb4d5ymrmQCGNbmFWeHHYGZvtB7VJuwnRiZHc64vN62cdO+AStQeCLVg==;"
    "EndpointSuffix=core.windows.net"
)
container_name = "hybris"


# Create blob client
blob_service_client = BlobServiceClient.from_connection_string(connection_string)
blob_client = blob_service_client.get_blob_client(container=container_name, blob=blob_name)

# Upload CSV
blob_client.upload_blob(csv_data, overwrite=True)
print("✅ DataFrame uploaded successfully as CSV (no header).")

In [ ]:
export_blob_name = "master/hotfolder/kickz/prices-{ts_millis}.csv"

In [ ]:
export_blob_name.format(ts_millis='dsdsd')

In [ ]:
import numpy as np
import pandas as pd
import settings.kickz as settings
from libs.help_functions import upload_dataframe_to_azure_blob_storage
from client_based_code.kickz_code import load_material_number_mapper,load_prices, get_orders
from libs.google_sheets import GoogleSheetsApi

In [ ]:
#a = load_prices()

In [ ]:
df = pd.read_parquet('backup/df_recommendations_20251103.parquet')

In [ ]:
df_dashboard = df

In [ ]:
df_dashboard['date'] = pd.to_datetime(df_dashboard['date']).dt.date
        
df_dashboard = df_dashboard[
    ['date','country_code','brand','product_name','style',
     'base_price','price','recom_price'
     ,'ads_ctr', 'ads_impressions',
     'category','item_category','item_group0','item_group1','item_group2'
]].round(2)

In [ ]:
df_orders  = get_orders(from_date=df_dashboard['date'].iloc[0])
df_orders['date'] = pd.to_datetime(df_orders['date']).dt.date

In [ ]:
df_dashboard = df_dashboard.merge(
    df_orders[['date','style','brand','quantity','country_code']].rename(columns={'quantity': 'sold_items_day'}),
    on = ['date', 'brand','style','country_code'],
    how = 'left'
)
df_dashboard['sold_items_day'] = df_dashboard['sold_items_day'].fillna(0)

In [ ]:
from libs.help_functions import upload_dataframe_to_azure_blob_storage

In [ ]:
dashboard_export_connection_string = (
    "DefaultEndpointsProtocol=https;"
    "AccountName=dlssynone11001;"
    "AccountKey=2VrwVvGrqX2XI/qjmaNuDyXQ3Pmnh1g67gq0rEAF3PQXFzoO6Rcl58de6zRGENMFFGjdcbgcxItP+AStCqWvgQ==;"
    "EndpointSuffix=core.windows.net"
)

In [ ]:
upload_dataframe_to_azure_blob_storage(
    df = df_dashboard,
    container_name = 'kickz-autopricing',
    blob_name = f"import/{df_dashboard['date'].unique()[0].isoformat()}.csv",
    connection_string = dashboard_export_connection_string,
    header=True
)

In [ ]:
df[df['style'].str.contains('60360504')][['brand','product_name','style','price', 'base_price','recom_price','country_code']]

In [ ]:
df_export = pd.read_parquet('ap_export.parquet')

In [ ]:
df[df['export_country_code'] == 'kickz-DE']

In [ ]:
df_export = df[
    (df['export_country_code'] == 'kickz-DE')
    &(df['material_number'].isin(['II5764-XL','II5764-L']))
]

In [ ]:
df_export['recom_price_local_currency'] = 64.95

In [ ]:
df_export

In [ ]:
import datetime as dt

In [ ]:
upload_dataframe_to_azure_blob_storage(
    df_export,
    settings.export_container_name,
    settings.export_blob_name.format(ts_millis=int(dt.datetime.now(dt.timezone.utc).timestamp() * 1000)),
    settings.export_connection_string
)

In [ ]:
df[df['export_status'] == 'DISCOUNT']

In [ ]:
df['export_status'].value_counts()

In [ ]:
df.shape

In [ ]:
df.groupby(['material_number', 'export_country_code']).size().sort_values()

In [ ]:
df

In [ ]:
df = df[df['material_number'] != 'Not Defined']

In [ ]:
df[df['material_number'] == 'IJ5626-M']

In [ ]:
import datetime as dt

In [ ]:
df['export_country_code'].unique()

In [ ]:
df.head(100)['export_country_code'].unique()

In [ ]:
df.iloc[72:73]

In [ ]:
df.head(75)

In [ ]:
from client_based_code.kickz_code import load_material_number_mapper

In [ ]:
df_mn = load_material_number_mapper()

In [ ]:
df_mn[df_mn['material_number'] == 'IJ5626-K2XL']

In [ ]:
df2 = pd.read_csv('prices-1759372237007.csv')

In [ ]:
df

In [ ]:
df2.iloc[71:72]

In [ ]:
from libs.help_functions import get_conversion_rates
import pandas as pd
from client_based_code.kickz_code import load_prices, load_material_number_mapper

In [ ]:
conversion_rates = get_conversion_rates()

df_conersion_rates = pd.DataFrame(conversion_rates, index=['conversion_rate'])\
                           .transpose()\
                           .reset_index()\
                           .rename(columns={'index': 'currency'})

In [ ]:
df_prices = load_prices()
df_prices = df_prices.merge(df_conersion_rates, on='currency')

In [ ]:
df_prices['price_EUR'] = df_prices['price_local'] / df_prices['conversion_rate']
df_prices['base_price_EUR'] = df_prices['base_price_local'] / df_prices['conversion_rate']

In [ ]:
df_prices[df_prices['style'].str.contains('bzco')]['style'].unique()

In [ ]:
df_manual_base_price = pd.read_csv(
    'BUCKETZ AUTOMATIC P D2(BUCKETZ).csv', 
    sep=';', 
    usecols=['material_number','UVP_KICKZ_EUR'],
    decimal = ','
)

In [ ]:
df_manual_base_price.dtypes

In [ ]:
df_material_number = load_material_number_mapper()
df_manual_base_price = pd.read_csv('BUCKETZ AUTOMATIC P D2(BUCKETZ).csv', sep=';')
df_manual_base_price = df_manual_base_price[['material_number','UVP_KICKZ_EUR']].merge(df_material_number, on='material_number')
df_prices = df_prices.merge(df_manual_base_price, on='style', how='left')
df_prices.loc[df_prices['UVP_KICKZ_EUR'].notna(), 'base_price_EUR'] = df_prices.loc[df_prices['UVP_KICKZ_EUR'].notna(), 'UVP_KICKZ_EUR']

In [ ]:
import pandas as pd
from client_based_code.kickz_code import load_prices

In [ ]:
df = pd.read_csv('data_for_pricing_last_run.csv')

In [ ]:
df

In [ ]:
df_prices = load_prices()

In [ ]:
df_prices[df_prices['style'].isin(df['style'])]

In [14]:
import pandas as pd
import logging
import sentry_sdk
from sentry_sdk.integrations.logging import LoggingIntegration
from libs.logger import Logger
from update_prices import PricingLogic
from settings import kickz
import datetime as dt

# 10 minut po polnoci kazdy den okrem nedele
"""
CRON: 10 2 * * 1,2,3,4,5,6 cd /home/ec2-user/autopricing-kickz/ && /home/ec2-user/anaconda3/bin/python run_update_prices.py
"""


# logging
logger = Logger().get_full_logger(
    filename='./logs/update_prices.log',
    log_level=logging.INFO,
    print_level=logging.INFO
)

In [15]:
updater = PricingLogic(settings=kickz)
self = updater

In [16]:
self.run_time = (self._get_current_time() - dt.timedelta(days=1)).replace(hour=23, minute=59)
        
logger.info('loading data started...')
self._load_data()

2026-04-20 08:02:40 - root - <module> - INFO - loading data started...
2026-04-20 08:02:40 - update_prices - _load_data - INFO - loading conversion rates...
2026-04-20 08:02:41 - update_prices - _load_data - INFO - loading data from google sheets...
2026-04-20 08:02:48 - libs.google_sheets - google_sheet2df - WARNING - Data not found in discount_levels_override!
2026-04-20 08:02:52 - libs.google_sheets - google_sheet2df - WARNING - Data not found in INDOOR_SHOES_discounts!
2026-04-20 08:02:52 - libs.google_sheets - google_sheet2df - WARNING - Data not found in ST_settings!
2026-04-20 08:02:52 - libs.google_sheets - google_sheet2df - WARNING - Data not found in destroy_competitors!
2026-04-20 08:02:53 - libs.google_sheets - google_sheet2df - WARNING - Data not found in pricing_groups_settings!
2026-04-20 08:02:53 - libs.google_sheets - google_sheet2df - WARNING - Data not found in ST_season_length_override!
2026-04-20 08:02:53 - update_prices - _load_data - INFO - loading data from google ads...
/home/ec2-user/autopricing-kickz/client_based_code/kickz_code.py:343: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(SQL,con)
/home/ec2-user/autopricing-kickz/client_based_code/kickz_code.py:343: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(SQL,con)
/home/ec2-user/autopricing-kickz/client_based_code/kickz_code.py:343: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(SQL,con)
2026-04-20 08:16:24 - update_prices - _load_data - INFO - loading products_to_score data from S3
2026-04-20 08:16:24 - botocore.credentials - load - INFO - Found credentials from IAM Role: ec2-role
2026-04-20 08:16:24 - client_based_code.kickz_code - load_latest - INFO - Loading: s3://autopricing/kickz/products_to_score/20260419210856.parquet...
2026-04-20 08:16:24 - aiobotocore.credentials - load - INFO - Found credentials from IAM Role: ec2-role
2026-04-20 08:16:30 - update_prices - _load_data - INFO - loading orders...
/home/ec2-user/autopricing-kickz/client_based_code/kickz_code.py:280: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(SQL,con)
2026-04-20 08:17:03 - update_prices - _load_data - INFO - loading quantity in inventory...
/home/ec2-user/autopricing-kickz/client_based_code/kickz_code.py:181: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(SQL,c)
/home/ec2-user/autopricing-kickz/client_based_code/kickz_code.py:181: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(SQL,c)
2026-04-20 08:20:26 - update_prices - _load_data - INFO - loading competitors data...
2026-04-20 08:20:26 - libs.bq - get_data_from_query - INFO - Running query and fetching results.
2026-04-20 08:20:40 - update_prices - _load_data - INFO - loading our prices...
/home/ec2-user/autopricing-kickz/client_based_code/kickz_code.py:437: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(SQL, c)
/home/ec2-user/autopricing-kickz/client_based_code/kickz_code.py:37: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(SQL,con)
2026-04-20 08:21:53 - update_prices - _load_data - INFO - loading rcmnd history...
2026-04-20 08:21:53 - client_based_code.kickz_code - load - INFO - Rcmnd history loading s3://autopricing/kickz/rcmnd_history/20260416.parquet...
2026-04-20 08:21:54 - client_based_code.kickz_code - load - INFO - Rcmnd history loading s3://autopricing/kickz/rcmnd_history/20260417.parquet...
2026-04-20 08:21:54 - client_based_code.kickz_code - load - INFO - Rcmnd history loading s3://autopricing/kickz/rcmnd_history/20260419.parquet...
2026-04-20 08:21:54 - update_prices - _load_data - INFO - loading past sell power...
2026-04-20 08:21:54 - update_prices - _load_data - INFO - loading last changed days ago...
2026-04-20 08:21:54 - update_prices - _load_data - INFO - loading style items categories...
/home/ec2-user/autopricing-kickz/client_based_code/kickz_code.py:383: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(SQL, c)

In [ ]:
logger.info('computing sold items...')
self._compute_sold_items()

logger.info('computing latest purchase cost...')
self._compute_style_latest_purchase_cost()

logger.info('computing first products order...')
self._compute_first_product_order()

logger.info('computing competitors comparison...')
self._compute_competitors_comparison(min_price=0,max_price=1000)

logger.info('computing gapi_714_ratios...')
self._compute_gapi_714_ratios()

logger.info('creating data for pricing...')
self._create_data_for_pricing()

In [ ]:
self.data_for_pricing[0]

In [31]:
self.prices_with_VAT.get(('ij5627','BE'))

{'price_EUR': 22.95, 'base_price_EUR': 22.95, 'price_local': 22.95}

In [ ]:
df_prices[df_prices['style'] == 'ij5627']

In [ ]:
df['country_code'].unique()

In [ ]:
df_prices['country_code'].unique()

In [24]:
import pandas as pd 
from client_based_code.kickz_code import load_prices,load_material_number_mapper

puma 777997-01 - produckt nie je v [rawKickz].[product_sales_price], nevieme ziskat rrp ani aktualnu cenu
puma 626685-65 - to iste
adidas original hk6694 - to iste
C.p. Company 16CMSB181A110039G-649 - to iste
C.p. Company 16CMSB181A110039G-913 - to iste
C.p. Company 14CMBW005A006369G-509 - to iste
fcpo5532-mnnyypppbro - to iste
BR-1325-10005-002 - to iste
BR-10000-100 - to iste
way of wade abas083-36 - novy produkt pridany do databazy 2026-03-12, tie ceny sme nenastavovali my, AP ho neskoroval
new era 70982808 - AP doporucil vo vsetkych krajinach nastavit cenu na RRP
under armour 1376784-007 - AP doporucil vo vsetkych krajinach nastavit cenu na RRP
adidas originals jp8000 - - AP doporucil vo vsetkych krajinach nastavit cenu na RRP
produkt 'A10596C-A10596C' neexistuje - asi si myslel converse A10596C-A1059

In [23]:
df_prices = load_prices()
#df = pd.read_parquet('backup/df_recommendations_20260319.parquet')

NameError: name 'load_prices' is not defined

In [ ]:
df_material_number = load_material_number_mapper()

In [ ]:
df_recommendations = df[df['style'].str.contains('br-1510')][['country_code','brand','product_name','style','base_price','recom_price']]

In [ ]:
df_export = df_recommendations.merge(df_material_number, on=['brand','style'])

In [ ]:
df_export.to_csv('autopricing_br-1510-10004.csv', index=False)

In [ ]:
df_export

In [8]:
style = ['dy6620']

In [9]:
item_category = get_style_items_categories(style, as_dict=True)

In [10]:
print(item_category)

{}

In [12]:
df_products_to_score = S3ProductsToScore.load_latest()

NameError: name 'S3ProductsToScore' is not defined

In [17]:
df = pd.read_parquet('backup/df_recommendations_20260420.parquet')

In [18]:
df.columns

Index(['brand', 'product_name', 'style', 'price', 'price_from', 'base_price',
       'price_original_currency', 'category', 'country_code', 'product_demand',
       'style_demand', 'impressions_demand', 'ctr_demand', 'total_demand',
       'total_sold_items', 'sold_items_day', 'sold_items_7_days',
       'sold_items_14_days', 'sold_items_season', 'sold_inventory_7_ratio',
       'quantity_in_inventory', 'quantity_in_inventory_7days',
       'quantity_in_inventory_ratio', 'is_new_product', 'ads_clicks',
       'ads_ctr', 'ads_impressions', 'season_length', 'days_from_season_start',
       'nodes_path', 'product_count_all_competitors',
       'product_count_important_competitors', 'product_all_competitors_list',
       'product_all_competitors_links', 'product_all_competitors_prices',
       'product_all_competitors_in_stock',
       'product_all_competitors_price_change_day',
       'product_important_competitors_list',
       'product_important_competitors_links',
       'product_important_competitors_prices',
       'product_important_competitors_in_stock',
       'product_important_competitors_price_change_day',
       'style_count_all_competitors', 'style_count_important_competitors',
       'style_all_competitors_list', 'style_all_competitors_links',
       'style_all_competitors_prices', 'style_all_competitors_in_stock',
       'style_all_competitors_price_change_day',
       'style_important_competitors_list', 'style_important_competitors_links',
       'style_important_competitors_prices',
       'style_important_competitors_in_stock',
       'style_important_competitors_price_change_day', 'sell_through_week',
       'sell_power_week', 'sell_through_day', 'sell_power_day',
       'max_discount_ST', 'min_discount_ST', 'ST_setting', 'ST_rate_pct',
       'ST_discount_level', 'last_day_sell_power_week', 'overriden_discount',
       'min_discount', 'max_discount', 'last_changed_days_ago',
       'changed_last_days', 'diff_to_expected_margin', 'purchase_price',
       'expected_margin', 'expected_margin_use_in_country', 'master_switch',
       'item_category', 'item_group0', 'item_group1', 'item_group2',
       'demand_key', 'demand_key_original', 'group_logic', 'recom_change',
       'recom_price', 'date'],
      dtype='object')

In [37]:
import numpy as np

In [57]:
df[df['price'].isna()]

,brand,product_name,style,price,price_from,base_price,price_original_currency,category,country_code,product_demand,...,item_category,item_group0,item_group1,item_group2,demand_key,demand_key_original,group_logic,recom_change,recom_price,date
0,adidas,adidas 3 stripes ankle 3er pack socks black,jv7436,NaN,NaN,NaN,NaN,CARRYOVERS,AT,0.0,...,lifestyle,EQUIPMENT,socksinclpacks,anklesock,jv7436,jv7436,OFF,NOT ENOUGH DATA,NaN,2026-05-03 23:59:02
1,adidas,adidas 3 stripes ankle 3er pack socks black,jv7436,NaN,NaN,NaN,NaN,CARRYOVERS,FR,0.0,...,lifestyle,EQUIPMENT,socksinclpacks,anklesock,jv7436,jv7436,OFF,NOT ENOUGH DATA,NaN,2026-05-03 23:59:02
2,adidas,adidas 3 stripes ankle 3er pack socks black,jv7436,NaN,NaN,NaN,NaN,CARRYOVERS,DE,0.0,...,lifestyle,EQUIPMENT,socksinclpacks,anklesock,jv7436,jv7436,OFF,NOT ENOUGH DATA,NaN,2026-05-03 23:59:02
3,adidas,adidas 3 stripes ankle 3er pack socks black,jv7436,NaN,NaN,NaN,NaN,CARRYOVERS,CH,0.0,...,lifestyle,EQUIPMENT,socksinclpacks,anklesock,jv7436,jv7436,OFF,NOT ENOUGH DATA,NaN,2026-05-03 23:59:02
4,adidas,adidas 3 stripes ankle 3er pack socks black,jv7436,NaN,NaN,NaN,NaN,CARRYOVERS,GB,0.0,...,lifestyle,EQUIPMENT,socksinclpacks,anklesock,jv7436,jv7436,OFF,NOT ENOUGH DATA,NaN,2026-05-03 23:59:02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32120,urban classics,urban classics urban classic raglan padded jac...,tb5906-tb5906,NaN,NaN,NaN,NaN,TOTAL_CLEARANCE,AT,0.0,...,Lifestyle,Apparel,Jacket Winter,Puffer Jacket,tb5906-tb5906,tb5906-tb5906,OFF,NOT ENOUGH DATA,NaN,2026-05-03 23:59:02
32121,urban classics,urban classics urban classic raglan padded jac...,tb5906-tb5906,NaN,NaN,NaN,NaN,TOTAL_CLEARANCE,FR,0.0,...,Lifestyle,Apparel,Jacket Winter,Puffer Jacket,tb5906-tb5906,tb5906-tb5906,OFF,NOT ENOUGH DATA,NaN,2026-05-03 23:59:02
32122,urban classics,urban classics urban classic raglan padded jac...,tb5906-tb5906,NaN,NaN,NaN,NaN,TOTAL_CLEARANCE,DE,0.0,...,Lifestyle,Apparel,Jacket Winter,Puffer Jacket,tb5906-tb5906,tb5906-tb5906,OFF,NOT ENOUGH DATA,NaN,2026-05-03 23:59:02
32123,urban classics,urban classics urban classic raglan padded jac...,tb5906-tb5906,NaN,NaN,NaN,NaN,TOTAL_CLEARANCE,CH,0.0,...,Lifestyle,Apparel,Jacket Winter,Puffer Jacket,tb5906-tb5906,tb5906-tb5906,OFF,NOT ENOUGH DATA,NaN,2026-05-03 23:59:02
32124,urban classics,urban classics urban classic raglan padded jac...,tb5906-tb5906,NaN,NaN,NaN,NaN,TOTAL_CLEARANCE,GB,0.0,...,Lifestyle,Apparel,Jacket Winter,Puffer Jacket,tb5906-tb5906,tb5906-tb5906,OFF,NOT ENOUGH DATA,NaN,2026-05-03 23:59:02

In [27]:
pd.set_option('display.max_columns', None)

In [32]:
self.prices_with_VAT.get(('jr1598','DE'))

In [33]:
print(self.prices_with_VAT.get(('jr1598','DE')))

None

In [31]:
from client_based_code.kickz_code import load_prices, get_prices_with_VAT

In [25]:
df_prices = load_prices()

/home/ec2-user/autopricing-kickz/client_based_code/kickz_code.py:437: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(SQL, c)

In [56]:
df_prices[df_prices['style'] == "ct8529-001"]

            style country_code currency  price_local  base_price_local
16489  ct8529-001           AT      EUR       149.95            209.95
16490  ct8529-001           BE      EUR       149.95            209.95
16491  ct8529-001           DE      EUR       149.95            209.95
16492  ct8529-001           DK      EUR       149.95            209.95
16493  ct8529-001           ES      EUR       149.95            209.95
16494  ct8529-001           FI      EUR       149.95            209.95
16495  ct8529-001           IT      EUR       149.95            209.95
16496  ct8529-001           NL      EUR       149.95            209.95
16497  ct8529-001           NO      EUR       149.95            209.95
16498  ct8529-001           SE      EUR       149.95            209.95

In [32]:
df_prices_with_vat = get_prices_with_VAT()

TypeError: get_prices_with_VAT() missing 1 required positional argument: 'pricing_logic_data'

In [34]:
from update_prices import PricingLogic
from settings import kickz

updater = PricingLogic(settings=kickz)

In [40]:
class S3ProductsToScore:
    BUCKET_NAME = 'autopricing'
    CLIENT = 'kickz'
    FOLDER = 'products_to_score'
    DATE_FORMAT = '%Y%m%d%H%M%S'
                
    @staticmethod
    def store(df):
        timestamp = dt.datetime.now().strftime(S3ProductsToScore.DATE_FORMAT)
        
        # convert to str
        cols = df.select_dtypes('object').columns.tolist()
        df[cols] = df[cols].astype(str)
        
        
        full_path = f's3://{S3ProductsToScore.BUCKET_NAME}/{S3ProductsToScore.CLIENT}/{S3ProductsToScore.FOLDER}/{timestamp}.parquet'
        logger.info(f"Storing: {full_path}...")
            
        df.to_parquet(path=full_path, compression='gzip', index=False)
            
            
    @staticmethod        
    def load_latest(columns=None, query=None, **kwargs):     
        file_names = sorted(
            [
                filename for filename in S3.get_all_objects_from_bucket(
                    bucket_name = S3ProductsToScore.BUCKET_NAME, 
                    prefix = f'{S3ProductsToScore.CLIENT}/{S3ProductsToScore.FOLDER}', 
                    only_keys=True
                )
                if filename.endswith('.parquet')
            ]
        )
        
        # latest one
        full_path = f's3://{S3ProductsToScore.BUCKET_NAME}/{file_names[-1]}'
        logger.info(f"Loading: {full_path}...")
        
        df = pd.read_parquet(
            full_path, 
            columns = columns, 
            **kwargs
            )
        
        if query is not None:
            df = df.query(query)
        
        return df.replace('None', np.nan)

In [41]:
df_products_to_score = S3ProductsToScore.load_latest()

2026-05-04 10:34:46 - botocore.credentials - load - INFO - Found credentials from IAM Role: ec2-role
2026-05-04 10:34:46 - root - load_latest - INFO - Loading: s3://autopricing/kickz/products_to_score/20260503210912.parquet...
2026-05-04 10:34:47 - aiobotocore.credentials - load - INFO - Found credentials from IAM Role: ec2-role

In [42]:
df_products_to_score = df_products_to_score.drop_duplicates(subset=['style'], keep = 'last')
df_products_to_score['date_added'] = pd.to_datetime(df_products_to_score['date_added'])
updater.styles = df_products_to_score['style'].str.lower().unique().tolist()

In [45]:
from libs.help_functions import (
    get_conversion_rates,)
updater.conversion_rates = get_conversion_rates()

In [46]:
updater._load_prices_with_VAT()

/home/ec2-user/autopricing-kickz/client_based_code/kickz_code.py:437: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(SQL, c)
/home/ec2-user/autopricing-kickz/client_based_code/kickz_code.py:37: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(SQL,con)

In [52]:
current_price = updater.prices_with_VAT.get(("jr1598", "DE"),{}).get('price_EUR',np.nan)

In [53]:
current_price

nan